---

- name: add rsyslog forwarding rule
  template:
    src: "rsyslog/forward_rule.conf.j2"
    dest: /etc/rsyslog.d/{{ rsyslog_forward_rule_name }}
    mode: "0644"
  notify:
    - restart rsyslog
  when: rsyslog_server_hostname != "changeme"
